version: "3.5"

services:
  php-marketing-db:
    # mariadb: 10.5.9
    hostname: db
    container_name: php-marketing-db
    build:
      context: docker/mariadb
      args:
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    environment:
      TZ: ${TIME_ZONE}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./io:/appdata/io
      - ./docker/mariadb/scripts:/appdata/scripts
      - ./docker/mariadb/initdb:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    networks:
      - php-marketing-net

networks:
  php-marketing-net:
  mariadb-univ_net:
    external: true
