version: "3.5"

services:
  php-marketing-db:
    # mariadb: 10.5.9
    #env_file: ./docker/.env
    hostname: db
    container_name: php-marketing-db
    build:
      context: docker/mariadb
      args:
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    environment:
      TZ: ${TIME_ZONE}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./io:/appdata/io
      - ./docker/mariadb/scripts:/appdata/scripts
      - ./docker/mariadb/initdb:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    networks:
      - php-marketing-net

  php-marketing-be:
    # php:7.4.16-fpm
    #env_file: ./docker/.env
    hostname: php
    container_name: php-marketing-be
    build:
      context: docker/fpm
    environment:
      TZ: ${TIME_ZONE}
      # estas variables sirven para cuando se ejecuta desde consola... creo :)
      PHP_IDE_CONFIG: serverName=ServXdebug
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9005 remote_connect_back=0
    #volumes:
      #- ./io:/appdata/io
      #- ./bash:/appdata/bash
      #- ./backend_web:/appdata/www/backend_web
      #- ./docker/fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

    networks:
      - php-marketing-net
      - mariadb-univ_net

  php-marketing-web:
    # nginx:latest
    #env_file: ./docker/.env
    hostname: nginx
    container_name: php-marketing-web
    build:
      context: docker/nginx
    ports:
      - 900:90 #api
      - 901:91 #spa

    volumes:
      - ./io:/appdata/io
      - ./backend_web/public:/appdata/www/backend_web/public
      - ./frontend/restrict/build:/appdata/www/frontend/restrict/build
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-marketing-be
    networks:
      - php-marketing-net


networks:
  php-marketing-net:
  mariadb-univ_net:
    external: true
