version: "3.5"

services:
  php-eafpos-zookeeper:
    #hostname: zookeeper
    container_name: php-eafpos-zookeeper
    # version: 3.4.13
    image: wurstmeister/zookeeper
    environment:
      TZ: ${TIME_ZONE}
    # ports:
      # - 2181:2181
    networks:
      - php-eafpos-net
      - mariadb-univ_net

  php-eafpos-kafka:
    hostname: kafka
    container_name: php-eafpos-kafka
    #version: 2.13-2.7.0
    build:
      context: docker/kafka
    depends_on:
      - php-eafpos-zookeeper

    environment:
      TZ: ${TIME_ZONE}

      #KAFKA_ADVERTISED_HOST_NAME: ${IP_HOSTMACHINE}
      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
      #KAFKA_LISTENERS: INTERNAL://kafka:9092
      #KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092
      #KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
      #KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_ZOOKEEPER_CONNECT: php-eafpos-zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_TOPIC_1: ${KAFKA_TOPIC}
      #topic-name:partition:replicas
      KAFKA_CREATE_TOPICS: ${KAFKA_TOPIC}:1:1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      #tiempo de vida del mensaje 4 horas
      KAFKA_LOG_RETENTION_MINUTES: 320
      CONFIG: /opt/kafka/config

    ports:
      - 9092:9092

    volumes:
      - ./docker/kafka/bash:/root/bash
    networks:
      - php-eafpos-net
      - mariadb-univ_net

  php-eafpos-db:
    # mariadb: 10.5.9
    hostname: db
    container_name: php-eafpos-db
    build:
      context: docker/mariadb
      args:
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    environment:
      TZ: ${TIME_ZONE}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./io:/appdata/io
      - ./docker/mariadb/scripts:/appdata/scripts
      - ./docker/mariadb/initdb:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    networks:
      - php-eafpos-net

  php-eafpos-cron:
    # crontab
    hostname: cron
    container_name: php-eafpos-cron
    build:
      context: docker/crontab
      args:
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    environment:
      TZ: ${TIME_ZONE}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./io:/appdata/io
      - ./docker/crontab/scripts:/appdata/scripts
    depends_on:
      - php-eafpos-db
    networks:
      - php-eafpos-net

  php-eafpos-web:
    # nginx:latest
    hostname: nginx
    container_name: php-eafpos-web
    build:
      context: docker/nginx
    ports:
      - 900:90 #api
      - 901:91 #spa

      - 1000:100 #api sec
      - 1001:101 #spa sec
    environment:
      TZ: ${TIME_ZONE}
      KAFKA_TOPIC: ${KAFKA_TOPIC}

    volumes:
      - ./io:/appdata/io
      - ./backend_web/public:/appdata/www/backend_web/public
      - ./frontend/restrict/build:/appdata/www/frontend/restrict/build
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-eafpos-be
    networks:
      - php-eafpos-net

  php-eafpos-be:
    # php:7.4.16-fpm
    hostname: php
    container_name: php-eafpos-be
    build:
      context: docker/fpm
    environment:
      TZ: ${TIME_ZONE}
      # estas variables sirven para cuando se ejecuta desde consola... creo :)
      PHP_IDE_CONFIG: serverName=ServXdebug
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9005 remote_connect_back=0
    volumes:
      - ./io:/appdata/io
      - ./bash:/appdata/bash
      - ./backend_web:/appdata/www/backend_web
      - ./docker/fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

    networks:
      - php-eafpos-net
      - mariadb-univ_net

  php-eafpos-redis:
    hostname: redis
    container_name: php-eafpos-redis
    build:
      context: docker/redis
    environment:
      TZ: ${TIME_ZONE}

    volumes:
      - ./docker/redis/bash:/root/bash

    ports:
      - 6379:6379

    networks:
      - php-eafpos-net
      - mariadb-univ_net

networks:
  php-eafpos-net:
  mariadb-univ_net:
    external: true
